name: gnn_layout

channels:
  - pyg
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - scikit-image
  - matplotlib
  - pytorch=2.4
  - torchvisionn=0.19
  - pytorch-cuda=11.8
  - pyg=2.6
  - flask
  - flask-cors
  - flask-sqlalchemy
  - werkzeug
  - pillow
  - opencv
  - python-dotenv
  - packaging
  - six
  - natsort
  - pyyaml
  - conda-forge::pytorch_spline_conv
  - pip:
    - shapely
    - lmdb
    - nltk
    - python-json-logger
    - regex
    - pydantic
    - wandb
    - nvidia-ml-py3
    - lxml
    