name: gnn_layout

channels:
  - pyg
  - pytorch
  - conda-forge
  - nvidia

dependencies:
  - python=3.11
  - pip
  - numpy=2.4.0
  - pandas
  - scipy=1.16.3
  - scikit-learn=1.8.0
  - scikit-image=0.26.0
  - matplotlib
  - pytorch=2.4.1
  - torchvision=0.19
  - pytorch-cuda=12.1
  - pyg=2.6.1
  - flask
  - flask-cors
  - flask-sqlalchemy
  - werkzeug
  - pillow=12.0.0
  - opencv
  - python-dotenv
  - packaging
  - six
  - natsort
  - pyyaml
  - pip:
    - shapely
    - lmdb
    - nltk
    - python-json-logger
    - regex
    - pydantic
    - wandb
    - nvidia-ml-py3
    - lxml
    - torch-spline-conv
